### ISSUE TITLE
Link naar homepage niet werkend in header en 404 pagina

### ISSUE THREAD

**Issue by Rhydium** [minvws/nl-covid19-coronacheck-website#11]
Wanneer je (op welke pagina dan ook) bovenin op het Rijksoverheid logo klikt kom je uit op een 404 pagina, deze foto redirect namelijk naar `coronacheck.nl/nl` ipv `coronacheck.nl/nl/` waardoor je op de 404 pagina uit komt. Wanneer je dan op deze pagina op de link klikt om naar de homepage te komen krijg je precies hetzelfde.

**Comment by anneke** [comment]
Hoi @Rhydium , Tijn, bedankt voor je feedback! Ik ga het gelijk nakijken en aanpassen!

**Comment by anneke** [comment]
We hebben een release in gang gezet waarbij dit wordt meegenomen, nogmaals bedankt: 

https://github.com/minvws/nl-covid19-coronacheck-website/releases/tag/v1.3.1
