### ISSUE TITLE
500 error klikken op QR-code maken"

### ISSUE THREAD

**Issue by sonar98** [minvws/nl-covid19-coronacheck-website#37]
### Describe the bug, issue or concern

Vanaf vandaag staat de data voor iemand die corona gehad heeft en een vaccinatie de waarde van completedByPersonalStatement in de data van het RIVM. De waarde staat op "Ja" maar sinds dit erin staat gaat het maken van een qr-code niet meer. Mijn eerste ingeving is dat er waarschijnlijk een 0 of een 1 verwacht wordt verderop in het proces maar er staat nu "Ja"

### To Reproduce
1. Zowel in de app als op de website login
2. haal de gegevens op
3. Druk op QR-CODE MAKEN
4. See error: print sign error

### Screenshots
![image](https://user-images.githubusercontent.com/645403/123666877-e617ff80-d839-11eb-8818-1979e46fd934.png)

### Governance
- [X ] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Hoi @sonar98 , bedankt voor je tip! We gaan hier naar kijken :)

**Comment by anneke** [comment]
@sonar98 ik heb begrepen dat dit bij de GGD is neergelegd en die hebben toegezegd dit binnen een half uur op te lossen!

**Comment by sonar98** [comment]
Yes nu werkt het wel.

**Comment by anneke** [comment]
Top! Dan sluit ik deze issue!
