### ISSUE TITLE
Cannot retrieve GGD PCR negative test, Please fix! 

### ISSUE THREAD

**Issue by Karimmaatouk15** [minvws/nl-covid19-coronacheck-website#39]
Please provide us with a way to show proof as many of us are traveling today!

**Comment by nicktencate** [comment]
Hi Karim,

Please see https://coronacheck.nl/nl/ for updates.

Kind regards,
Nick

**Comment by Karimmaatouk15** [comment]
Hey Nick, 
It is still not working. 

Is there any alternative way to retrieve the proof for those of us traveling today?

**Comment by Chantalcg** [comment]
Hi Karim, 

For these type of questions in the future, please contact the CoronaCheck helpdesk. You can reach us at 0800-1421 (Monday to Sunday from 8 am - 8 pm) or via helpdesk@coronacheck.nl.
