### ISSUE TITLE
Privacy verklaring zeer mager en het is niet duidelijk waarom er meerdere varianten van zijn.

### ISSUE THREAD

**Issue by timostrating** [minvws/nl-covid19-coronacheck-website#4]
De privacy verklaringen zijn te vinden op:
https://github.com/minvws/nl-covid19-coronacheck-website/blob/main/nl/privacy-fieldlab.md
https://github.com/minvws/nl-covid19-coronacheck-website/blob/main/nl/privacy-in-app-fieldlab.md
https://github.com/minvws/nl-covid19-coronacheck-website/blob/main/nl/privacy-in-app.md
https://github.com/minvws/nl-covid19-coronacheck-website/blob/main/nl/privacy-in-app.md

Deze verschillen zijn haast niet van elkaar te herkennen. Het is daarom niet helemaal duidelijk waar en waarom er soms een verschil in zit.

Daarnaast staan een aantal onderdelen niet duidelijk genoeg omschreven:

_NR_1_
### "6. Wie heeft toegang tot de gegevens?"

"Het omzetten van het testresultaat naar een testbewijs, inclusief het digitaal tekenen van het testbewijs gebeurt bij Prolocation B.V. Prolocation verwerkt gegevens in opdracht van het ministerie van Volksgezondheid, Welzijn en Sport en heeft in AVG termen de rol van verwerker."

De rol van de verwerker Prolocation B.V staat hier niet duidelijk omschreven.

_NR_2_ 
### "7. Hoe lang worden gegevens bewaard?"

* Met digid wordt een acces token verkregen Hoe lang dit bewaard wordt staat niet omschreven. zie https://api-ct.bananenhalen.nl/overview/run/
* Er staat omschreven dat het testbewijs wordt verwijderd en wanneer. De afgeleide QR codes waar uit te halen is wanneer iemand een corona test heeft gedaan worden alleen niet expliciet vermeld. Dus wanneer worden deze verwijderd?
* Meerdere APi's worden aangesproken om uiteindelijk een QR code te verkrijgen. Wat deze loggen staat alleen om schreven als dat ze Ip adressen opslaan. Als dit zo is graag expliciet melden.

**Comment by nicktencate** [comment]
Ik zal vragen of ze dit wat duidelijker gaan verwerken in de privacy policy. Er bestonden meerdere varianten omdat er meerdere varianten van de CoronaCheck app tegelijk getest werden, dat is nu niet meer zo.

Hier al wat antwoorden:

NR_1 (eigenlijk 6):
- De rol van verwerker betekend dat zij IP adressen zien en strippen. Ze kunnen niet zien wat voor data er heen en weer gestuurd word. De TLS terminatie gebeurt bij VWS.

NR_2 (eigenlijk 7)
- De DigiD flow die daar omschreven staat is verouderd en er komt t.z.t. een nieuw sequence diagram.
- Aan de server kant loggen we (VWS) op dit moment niks. Zodra je test resultaat is omgezet naar een testbewijs, kunnen we niks meer over je terug vinden. Het IP adres word al weg gestript door Prolocation voor dat het verzoek om een test resultaat om te zetten in een test bewijs bij VWS komt, dus die hebben we ook niet.

**Comment by anneke** [comment]
Hoi @timostrating bedankt voor je reactie! In aanvulling op de reactie van Nick wil ik graag nog aanmerken dat we de privacystatements van de Fieldlab experimenten (de eerste twee links uit je bericht) op 'offline' staan, en daarmee alleen nog in deze repo voorkomen maar niet meer op de site.

**Comment by anneke** [comment]
@timostrating We hebben zojuist de privacy statement aangepast. Zou je willen kijken of je feedback nog actueel is? Dan geef ik dat door :)

**Comment by timostrating** [comment]
@anneke Bedankt voor de verbeteringen, Ik heb nog wel wat twijfels over de privacy, veiligheid en implementatie van bijvoorbeeld de "Digitale handtekening – deze wordt geplaatst om zeker te weten dat het testbewijs niet kan worden aangepast. De digitale handtekening is op zichzelf geen persoonsgegeven binnen het proces, maar het tekenen van een testresultaat is wel noodzakelijk voor de werking van CoronaCheck." Maar dat is meer een ander punt, alvast heel erg bedankt voor de aanpassingen.

**Comment by anneke** [comment]
Geen dank, jij bedankt @timostrating !
