### ISSUE TITLE
Inability to view vaccination information or create a QR code due to missing hpkCode?

### ISSUE THREAD

**Issue by koenhoeijmakers** [minvws/nl-covid19-coronacheck-website#40]
### Describe the bug, issue or concern
An error (`this.vaccination.hpkCode is null`) occurs when trying to view information about my vaccination, this also results in the inability to create a QR code.

### To Reproduce
1. Go to 'https://coronacheck.nl/nl/print/jouw-vaccinaties'
2. Click on The info button next to the vaccination to get more information
3. See the `this.vaccination.hpkCode is null` error in the console.

### Expected behavior
My vaccination information is displayed.

### Screenshots
![image](https://user-images.githubusercontent.com/2232776/124289487-ab240d80-db52-11eb-8178-08d7277d7950.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 10.0.19043
 - Browser: Firefox 
 - Version 89.0.2 (64-bit)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Bedankt voor de melding. Ik heb hem doorgezet naar de juiste afdeling. Zou je deze ook even via helpdesk@coronacheck.nl willen doormelden? Dan hebben we nog een aantal extra vragen. Graag expliciet naar mij vragen :)

**Comment by nicktencate** [comment]
Ticket heropend; bug report m.b.t. geen foutmelding op lege hpkCode moet opgelost worden. 

Het feit dat hpkCode ontbreekt heb ik doorgegeven; data is een data kwaliteit issue en niet onderdeel van dit ticket.

**Comment by koenhoeijmakers** [comment]
Hey Nick, De helpdesk is vooralsnog zeer onbehulpzaam geweest (de laatste 4 dagen), kan ik jou anders direct mailen (scheelt weer 2 dagen wachten op reactie)? Zo niet dan zal ik dat alsnog doen

**Comment by jeroenbreen** [comment]
@koenhoeijmakers als het goed is zou de bug op klik na vraagteken nu gefixet moeten zijn.
Helaas ligt het structurele probleem - de missende hpkCode-  buiten coronacheck.

**Comment by koenhoeijmakers** [comment]
@jeroenbreen klopt, dat probleem is inderdaad verholpen, de hpkCode is helaas nog altijd niet gelukt om opgelost te krijgen.

**Comment by koenhoeijmakers** [comment]
Ondertussen lijkt het probleem bij de GGD ook opgelost. Hoe of wat hun oplossing is geweest is voor mij onduidelijk maar dat is denk ik ook onrelevant.

Bedankt voor het meedenken!
