### ISSUE TITLE
Geen certificaat bij extra vaccinatie bijv. 2 van 1 of 4 van 2 bij een dubbele registratie

### ISSUE THREAD

**Issue by sonar98** [minvws/nl-covid19-coronacheck-website#44]
### Describe the bug, issue or concern
Als in het centrale systeem geregistreerd is dat je maar 1 vaccinatie nodig hebt omdat je een covid besmetting hebt gehad en je krijgt je 2e prik dan is je certificaat niet meer geldig. In de data staat dan vaccinatie 2 van 1.
Ook bij iemand waarbij de vaccinaties dubbel in het systeem staan gaat het fout dan staat er 4 van 2 en dan krijg je ook geen geldig (internationaal) certificaat als je dit scant met de scanner app.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Beste Sonar98; voor dit soort vragen kun je het beste terecht op de CoronaCheck helpdesk. Deze is beschikbaar op helpdesk@coronacheck.nl
