### ISSUE TITLE
Incorrect information about the scanning app

### ISSUE THREAD

**Issue by enricomiletto** [minvws/nl-covid19-coronacheck-website#45]
### Describe the bug, issue or concern
The subsection of [this page](https://coronacheck.nl/en/scanner) that specifies what to do in case a app shows a red screen upon scanning a QR code contains information that seems incorrect to me.

1. It is **not true** that only Dutch QR codes lead to a green screen. I have tried with my Swiss DCC and was shown green screen.

2. The app **doesn't** check whether that QR code was shown from inside the CoronoCheck app

### Screenshots
![Immagine 2021-07-28 112947](https://user-images.githubusercontent.com/80707578/127300310-46dc31ff-5178-4b18-b565-473ad2814b68.jpg)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Hi @enricomiletto , thank you for bringing this to our attention, we're going to take a look at this! Hopefully we can incorporate any changes with other updates we're preparing to that page this week.

**Comment by SleeplessByte** [comment]
In the meanwhile, I'm pretty sure it's the terminology, but not the intended content here that's wrong.

- With international QR I think the team meant "Dutch-data but generated for international use QR" / "QR generated with the Dutch CoronaCheck app set on the international setting" and not "QR that's not Dutch".
- Whilst the scanner does not check if the QR comes from an application, what's meant here is that screenshots or copies are likely to result in a red screen. Self-generated (self-signed) QR codes would also. But technically you're correct, as paper-qrs with the correct signature do also work, so the information is technically incorrect.

**Comment by enricomiletto** [comment]
@anneke @SleeplessByte thanks for taking the time to respond to my issue. I'm happy this is going to be taken care of.

@SleeplessByte about your second point, I do understand what you're saying, but the person who's DCC gets checked may not be Dutch and thus not have their QR code inside the Dutch app but inside the app of their home country (and some EU countries give out the DCC's only in paper form).

**Comment by SleeplessByte** [comment]
@enricomiletto I absolutely 100% agree that it's confusing for non-dutchies :) and thus it should be solved!

**Comment by anneke** [comment]
Hi @enricomiletto , I put it in front of our copy specialists and they have asked me to change the text next week to "Check whether the visitor shows a Dutch QR code.  Scanning an international QR code in the CoronaCheck-app will result in a red screen.". Does that clarify things? :)

**Comment by SleeplessByte** [comment]
@anneke that's technically incorrect. Scanning an internal non-Dutch QR code will result in a green screen.

**Comment by enricomiletto** [comment]
@SleeplessByte I think you meant to write international instead of interal

**Comment by SleeplessByte** [comment]
> @SleeplessByte I think you meant to write international instead of internal

I did, but my spellchecker didn't agree with the spelling mistake I made :p

**Comment by enricomiletto** [comment]
@SleeplessByte yeah I assumed that was the case :P

**Comment by enricomiletto** [comment]
@anneke As @SleeplessByte said, the sentence is not correct as the scanning app can verify Digital COVID Certifiates from all EU countries + Norway, Liechtenstein, Switerland and Iceland.

**Comment by enricomiletto** [comment]
From what you guys are writing I deduce that Dutch people can switch between a Netherlands-only QR Code and an International one inside the CoronaCheck app.
Is the "Dutch QR Code" inside the app a more "privacy preserving" version of the DCC only for internal use in the Netherlands? Or what's the purpose of having two different kinds of codes?

**Comment by SleeplessByte** [comment]
You got it.

The Dutch qr code is much more privacy friendly. For that reason, Dutch EU QRs (the thing we call international) are not scannable with the Dutch scanner to force people to use the more privacy friendly option.

For actuall international people it doesn't matter. Their EU qr will scan just fine.

**Comment by enricomiletto** [comment]
@anneke the sentence should be changed with something along the lines of 

> **If the visitor is a Dutch resident**, check that they are showing the Dutch QR code (the one for use in the Netherlands only)

**Comment by anneke** [comment]
@enricomiletto our copy team wants to change it to this:

```
Woont de bezoeker in Nederland? Controleer of de bezoeker een Nederlandse QR-code laat zien. Het scannen van een internationale QR-code in de CoronaCheck-app geeft een rood scherm.

Is the visitor a Dutch resident? Then check that they are showing the Dutch QR code. Scanning an international QR code in the CoronaCheck app will result in a red screen.
```

**Comment by enricomiletto** [comment]
Yes, they got the point. I don't think there's any way to misinterpret it like this

**Comment by SleeplessByte** [comment]
Sounds good to me too.

**Comment by anneke** [comment]
Alright, thank you very much @enricomiletto and @SleeplessByte ! We've prepared a release for tonight with this change in it. With that, I will consider this issue closed! Thanks again.
