### ISSUE TITLE
There exist both a `humans.txt` and `people.txt`

### ISSUE THREAD

**Issue by dvberkel** [minvws/nl-covid19-coronacheck-website#46]
### Difference between `humans.txt` and `people.txt`
I have a concern over the following two files in the root of the project

* `humans.txt`
* `people.txt`

The both seem to serve a similar purpose. `humans.txt` at least has some form of comment stating the intended purpose. The contents does not agree between both files

E.g. 

### To Reproduce
1. Go to the project [repository](https://github.com/minvws/nl-covid19-coronacheck-website)
2. See a `people.txt` and `humans.txt`

### Expected behavior
I would expect to see either a single file, are a clear an explanation of the difference of both file and their purpose.

### Additional context
It could be the case that one file should be generated from the other.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Hi dvberkel,

Thanks - seems we missed this one. Will be merged in the next release.
