### ISSUE TITLE
Printen op creditcard formaat

### ISSUE THREAD

**Issue by nielsbasjes** [minvws/nl-covid19-coronacheck-website#47]
### Describe the bug, issue or concern

Het "op papier" krijgen van de corona QR code resulteert in een PDF welke afgedrukt moet worden.

Het praktische probleem dat ik heb met deze PDF is dat het formaat van de uiteindelijke afdruk te groot is om handig mee te kunnen nemen.

In de gevouwen stand is het groter dan een normaal paspoort (je kan hem er dus niet tussen doen) en het is veel groter dan het 'creditcard formaat' van rijbewijzen en id kaarten en past daardoor in vrijwel geen van de gebruikelijke opberg systemen (zoals telefoon hoesjes).

Mijn praktische voorstel is om een extra afdruk formaat toe te voegen waar dezelfde gegevens geprint worden (de teksten en QR code precies hetzelfde) in een formaat dat de maat van een credit card heeft.

Feitelijk exact hetzelfde wat nu al bestaat alleen wordt de afdruk wat kleiner en moet het uitgeknipt worden.

Een dergelijke QR code op 5cm x 5cm past net op een creditcard en werd door alle telefoons die ik heb prima gescand.

Implementatie technisch zie ik op dit moment 3 routes:
- De standaard PDF wordt aangepast:
  - huidige formaat vervangen met de credit card 
    geen keuze: iedereen het kleinere formaat.
  - een extra pagina aan de print toevoegen met de credit card
    keuze: je krijgt altijd beide formaten en kies welke je gebruikt door te kiezen welke pagina je afdrukt.
- De vraag stellen voor het afdrukken welk formaat gewenst is.
  - En dus een 2e PDF formaat toevoegen met alleen de creditcard.
    keuze: je kiest van te voren welk formaat je wil.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Hoi Niels, even een verlate reactie. Ik heb rondgevraagd en dit idee is zeker gelezen, maar helaas heeft het team momenteel niet de tijd (gevonden) om hier mee aan de slag te gaan. Ik laat deze issue daarom voorlopig open staan.

**Comment by ijansch** [comment]
Dank je wel voor de suggestie. Voor de internationale QR zijn we gebonden aan een aantal richtlijnen vanuit Europa. Zo is er een template die europees breed als basis wordt gehanteerd voor herkenbaarheid, en zijn er eisen t.a.v. de geschreven informatie die er rond de QR moet staan.

Voor de Nederlandse QR zou dit wel toepasbaar zijn. Ook daar willen we echter wat informatie kwijt rond de QR die voor de meeste mensen relevant is, dus voor iedereen een kleiner formaat lijkt ons niet heel praktisch. De vraag is of de doelgroep voor wie dit nuttig is, dusdanig groot is dat we voor iedereen wat extra complexiteit moeten introduceren (elke keuze beinvloedt de complexiteit), terwijl de meesten die dit handig vinden, wel zo handig zijn om zelf de QR uit te knippen op een ander formaat. Ik zal het eens met het design team bespreken.

**Comment by nielsbasjes** [comment]
Deze site en app gaan we niet meer gebruiken. Dus ik close deze (ook wegens de lage prio enzo).
