### ISSUE TITLE
Php code not handled by webserver

### ISSUE THREAD

**Issue by basmilius** [minvws/nl-covid19-coronacheck-website#50]
### Describe the bug, issue or concern
Not sure if this is the correct repository, but raw PHP code is visible at status.coronacheck.nl. I think that this should be fixed.

### To Reproduce
1. Go to https://status.coronacheck.nl/app/auth.php

### Expected behavior
That the webserver executes the php script rather than showing it.

### Screenshots
![image](https://user-images.githubusercontent.com/978257/158334592-df93fa9d-3395-40b8-8591-8d69e1c1202c.png)

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Browser: Chrome
 - Version 99

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by nicktencate** [comment]
Hi Bas,

Thanks for finding this. It's an old script that has been deprecated, and now been removed.
